import ImageDisplay from '../../../components/ImageDisplay';
import { apiGet } from '../../../lib/api';

type GalleryPageProps = {
  params: {
    id: string;
  };
};

export default async function GalleryPage({ params }: GalleryPageProps) {
  const { id } = params;

  let data: any;
  try {
    data = await apiGet(`/image/${id}`);
  } catch (err) {
    return (
      <div className="page-shell">
        <div className="card stack">
          <p className="muted" style={{ letterSpacing: '0.08em' }}>
            GALLERY
          </p>
          <h1 style={{ fontSize: '1.75rem' }}>Artwork unavailable</h1>
          <p className="error">
            {(err as Error)?.message ||
              'We could not load this artwork. It might be private or has expired.'}
          </p>
          <a className="btn" href="/login">
            Generate your own
          </a>
        </div>
      </div>
    );
  }

  const imageUrl = data?.imageUrl || data?.url || data?.image;
  const title = data?.title || 'Blended album art';
  const description =
    data?.description ||
    'Generated by blending your Spotify favorites using Music Art Generator.';

  return (
    <div className="page-shell">
      <div className="card stack">
        <div className="stack" style={{ gap: '0.35rem' }}>
          <p className="muted" style={{ letterSpacing: '0.08em' }}>
            PUBLIC GALLERY
          </p>
          <h1 style={{ fontSize: '1.75rem' }}>{title}</h1>
          <p className="muted">{description}</p>
        </div>
        {imageUrl ? (
          <ImageDisplay
            src={imageUrl}
            alt={title}
            downloadName={title.replace(/\s+/g, '-').toLowerCase()}
          />
        ) : (
          <p className="error">
            Artwork found but missing an image URL. Please try again later.
          </p>
        )}
        <a className="btn" href="/generate">
          Make yours
        </a>
      </div>
    </div>
  );
}
